[package]
name = "memstapler"
version = "0.1.0"
edition = "2018"
rust-version = "1.56"

[dependencies]
unwrap_or = "1.0"
nix = { version = "0.30", features = ["mman", "sched"] }
anyhow = "1.0"

[profile.release]
debug = true
