[package]
name = "memstapler"
version = "1.0.0"
edition = "2018"
rust-version = "1.56"

[dependencies]
unwrap_or = "1.0"
nix = { version = "0.26", features = ["mman", "sched"] }
libc = "=0.2.151"
anyhow = "1.0"

[profile.release]
debug = true
